# Generated by Django 2.2.6 on 2019-10-15 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='email',
        ),
    ]
