# Generated by Django 2.2.6 on 2019-10-17 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_search_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='keyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyWord', models.CharField(max_length=270)),
            ],
        ),
    ]
