# Generated by Django 2.2.6 on 2019-12-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Busquedas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lenguaje', models.CharField(max_length=100)),
                ('palabraclave', models.CharField(max_length=140)),
                ('cantidadtweets', models.IntegerField()),
                ('fechadebusqueda', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
